name: Build GCC 15.1 from Source Tarball

on:
  workflow_dispatch:

jobs:
  build-gcc:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout (minimal untuk workspace)
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gawk flex bison \
          libgmp-dev libmpfr-dev libmpc-dev libisl-dev \
          zlib1g-dev libzstd-dev python3 tar gzip bzip2 perl

    - name: Download GCC Tarball
      run: |
        wget https://gcc.gnu.org/pub/gcc/releases/gcc-15.1.0/gcc-15.1.0.tar.xz
        tar -xf gcc-15.1.0.tar.xz

    - name: Download Prerequisites
      run: |
        cd gcc-15.1.0
        ./contrib/download_prerequisites

    - name: Configure Build
      run: |
        mkdir gcc-15-build
        cd gcc-15-build
        ../gcc-15.1.0/configure \
          --disable-multilib \
          --enable-languages=c,c++ \
          --prefix=$GITHUB_WORKSPACE/gcc-15-install

    - name: Build & Install
      run: |
        cd gcc-15-build
        make -j4        

    - name: Use GCC 15
      run: |
        echo "$GITHUB_WORKSPACE/gcc-15-install/bin" >> $GITHUB_PATH
        gcc --version
